site_name: JSTP
site_url: https://metarhia.github.io/jstp/
repo_url: https://github.com/metarhia/jstp/
edit_uri: edit/master/doc/
docs_dir: doc
pages:
  - Home: index.md
  - Formats: data-formats.md
  - Protocol: protocol.md
  - API:
    - 'Record Serialization': api/record-serialization.md
    - 'Object Serialization': api/object-serialization.md
    - 'Errors': api/errors.md
    - 'Authentication Providers': api/auth-provider.md
    - 'Applications and Application Providers': api/apps-provider.md
    - 'Remote Proxy': api/remote-proxy.md
    - 'Connection': api/connection.md
    - 'Server': api/server.md
    - 'Client': api/client.md
    - 'TCP Transport': api/transport.tcp.md
    - 'WebSocket Transport (Node.js)': api/transport.ws.md
    - 'WebSocket Transport (Browser)': api/transport.ws.browser.md
theme: readthedocs
